# Powerlevel10k prompt tuned for CachyOS / Arch vibe
# Generated 2025-11-12 — edit and reload with: source ~/.config/p10k.zsh

typeset -g POWERLEVEL9K_MODE=nerdfont-v3
typeset -g POWERLEVEL9K_ICON_PADDING=none
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=false
typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL='░▒▓'
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='�'
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='�'
typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL='▓▒░'
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='�'
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
typeset -g POWERLEVEL9K_VCS_USE_GITSTATUS=1
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
typeset -g POWERLEVEL9K_SHORTEN_DELIMITER='…'

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon
  dir
  vcs
  background_jobs
  prompt_char
)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  vi_mode
  time
)

typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=109
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=0

typeset -g POWERLEVEL9K_DIR_BACKGROUND=25
typeset -g POWERLEVEL9K_DIR_FOREGROUND=231
typeset -g POWERLEVEL9K_DIR_HYPERLINK=1
typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=yes
typeset -g POWERLEVEL9K_DIR_VISUAL_IDENTIFIER_EXPANSION=''

typeset -g POWERLEVEL9K_VCS_BACKGROUND=202
typeset -g POWERLEVEL9K_VCS_FOREGROUND=0
typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_VCS_STAGED_ICON='!'
typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='?'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
typeset -g POWERLEVEL9K_VCS_COMMITS_AHEAD_ICON='⇡'
typeset -g POWERLEVEL9K_VCS_COMMITS_BEHIND_ICON='⇣'
typeset -g POWERLEVEL9K_VCS_CONFLICTED_ICON='✖'
typeset -g POWERLEVEL9K_VCS_GIT_HOOKS=()

typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=239
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=220
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION=''

typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='%(!.#.❯)'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_CONTENT_EXPANSION='%(!.#.❮)'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION='✖'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_CONTENT_EXPANSION='✖'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=46
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND=39
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=196
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND=196

typeset -g POWERLEVEL9K_STATUS_OK=true
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=65
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=0
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=160
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=15
typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'
typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'
typeset -g POWERLEVEL9K_STATUS_OK_IN_NON_ZERO_STATE=true

typeset -g POWERLEVEL9K_VI_MODE_BACKGROUND=238
typeset -g POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND=46
typeset -g POWERLEVEL9K_VI_MODE_COMMAND_FOREGROUND=220
typeset -g POWERLEVEL9K_VI_MODE_VISUAL_FOREGROUND=208
typeset -g POWERLEVEL9K_VI_MODE_INSERT_PROMPT='I'
typeset -g POWERLEVEL9K_VI_MODE_COMMAND_PROMPT='N'
typeset -g POWERLEVEL9K_VI_MODE_VISUAL_PROMPT='V'

typeset -g POWERLEVEL9K_TIME_BACKGROUND=18
typeset -g POWERLEVEL9K_TIME_FOREGROUND=231
typeset -g POWERLEVEL9K_TIME_ICON=''
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=true

typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true
typeset -g POWERLEVEL9K_SHOW_RULER=false

# Keep instant prompt caches slim
[[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]] || return 0
